<?php

/**
 * @file
 * Testing for the rooms suite of modules 
 */


/**
 * Implements hook_menu().
 */
function rooms_test_menu() {
  $items = array();

  $items['admin/rooms/test/test1'] = array(
    'title' => 'Commerce Test',
    'description' => 'Create product and add to cart',
    'page callback' => 'rooms_test_commerce',
		'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access administration pages'),
  );
	
	
	$items['admin/rooms/test/test2'] = array(
    'title' => 'Availability Search Test',
    'description' => 'Search for availability',
    'page callback' => 'rooms_test_availability',
		'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access administration pages'),
  );
	
	
	$items['admin/rooms/test/test3'] = array(
    'title' => 'Event Update Tests',
    'description' => 'Tests for event update',
    'page callback' => 'rooms_test_event_update',
		'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access administration pages'),
  );

  return $items;
}


function rooms_test_availability() {
	
}


function rooms_test_event_update() {
	
}



function rooms_test_commerce(){
}