<?php

/**
 * @file
 * Provides basic underlying functionality and configuration options used
 * by all Rooms modules
 */


/**
 * Implements hook_permission().
 */
function rooms_permission() {
  $permissions = array(
    'configure rooms' => array(
      'title' => t('Configure rooms settings'),
      'description' => t('Allows users to configure rooms settings'),
      'restrict access' => TRUE,
    ),
  );

  return $permissions;
}


/**
 * Utility function that returns an array with the last day of each month given a year
 *
 * @param $year
 * The year to get the end of month dates for
 *
 * @param $calendar
 * The calendar to use to determine eof dates
 *
 * @return
 * An array keyed by months
 */
function rooms_end_of_month_dates($year) {
  
  $end_of_month_dates = array();
  
  for ($i = 1; $i<=12; $i++) {
     $end_of_month_dates[$i] = date("t", mktime(0, 0, 0, $i, 1, $year));
  }
  
  return $end_of_month_dates;
}

/**
 * Utility function - we have a few forms that need a start and end date field and we need to apply
 * the same javascript to these forms in order to have them behave a bit better.
 *
 * This groups the form elements and javascript injection in one place.
 */ 
function rooms_date_range_fields($date_range_fields = array()) {
  $date_range_fields['rooms_start_date'] = array(
    '#prefix' => '<div class="start-date">',    
    '#suffix' => '</div>',
    '#type' => 'date_popup',
    '#title' => t('Start Date'),
    '#date_type' => DATE_DATETIME,
    '#date_format' => 'Y/m/d',
    //'#default_value' => "$year-$month-01 00:00:00",
    '#date_increment' => 1,
    '#date_year_range' => '-1:+3',
    '#required' => TRUE,
  );
  

  $date_range_fields['rooms_end_date'] = array(
    '#prefix' => '<div class="end-date">',    
    '#suffix' => '</div>',
    '#type' => 'date_popup',
    '#title' => t('End Date'),
    '#date_type' => DATE_DATETIME,
    '#date_format' => 'Y/m/d',
    //'#default_value' => "$year-$month-01 00:00:00",
    '#date_increment' => 1,
    '#date_year_range' => '-1:+3',
    '#required' => TRUE,
  );
  
  drupal_add_js(array('rooms' => array('roomsBookingStartDay' => variable_get('rooms_booking_start_date', 1))), 'setting');
  drupal_add_js(drupal_get_path('module', 'rooms') . '/js/rooms_date_popup.js');


  return $date_range_fields;
}




