<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function rooms_listing_menu() {
  $items = array();

  return $items;
}

/**
 * Creates the listing type
 */
function rooms_listing_create_listing_type() {
  module_load_include('inc', 'rooms_listing', 'rooms_listing.fields');

  $listing_type = bat_unit_unit_type_new();

  $listing_type['type'] = 'listing';
  $listing_type['label'] = 'Listing';
  $listing_type['data'] = array (
    'hourly_availability' => 0,
    'pricing_field' => 'listing_nightly_price',
    'pricing_weekly_field' => 'listing_weekly_price',
    'pricing_monthly_field' => 'listing_monthly_price',
  );

  $bat_unit_type = bat_unit_type_create($listing_type);
  $bat_unit_type->save();

  // Create nightly pricing
  $description = t('This is the default nightly price for your listing');
  bat_unit_add_price_field('listing_nightly_price', 'bat_unit', $listing_type['type'], 'Nightly Price', $description, $weight = 0, $locked = TRUE, $calculation = FALSE, $display = array());

  // Create weekly pricing
  $description = t('This is the default weekly price for your listing');
  bat_unit_add_price_field('listing_weekly_price', 'bat_unit', $listing_type['type'], 'Weekly Price', $description, $weight = 1, $locked = TRUE, $calculation = FALSE, $display = array());

  // Create monthly pricing
  $description = t('This is the default monthly price for your listing');
  bat_unit_add_price_field('listing_monthly_price', 'bat_unit', $listing_type['type'], 'Monthly Price', $description, $weight = 2, $locked = TRUE, $calculation = FALSE, $display = array());

  rooms_listing_create_listing_fields();
}
