<?php

/**
 * @file
 * Manage Rooms for Rooms! 
 */  


/**
 * Implement hook_entity_info().
 */
function rooms_room_entity_info() {
  $return['rooms_room'] = array(
    'label' => t('Room'),
    // The entity class and controller class extend the classes provided by the
    // Entity API
    'entity class' => 'RoomsRoom',
    'controller class' => 'RoomsRoomController',
    'base table' => 'rooms',
    'fieldable' => TRUE,
    'entity keys' => array(
        'id' => 'room_id',
        'bundle' => 'type',
    ),
    // Bundles are defined by the room types below
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle objects
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 'rooms_room_create',
    'access callback' => 'rooms_room_access',
    'module' => 'rooms_room',
    // The information below is used by the RoomsRoomUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/rooms/rooms',
      'file' => 'rooms_room.admin.inc',
      'controller class' => 'RoomsRoomUIController',
      'menu wildcard' => '%rooms_room',
    ),
  );
  // The entity that holds information about the entity types	  
  $return['rooms_room_type'] = array(
    'label' => t('Room Type'),
    'entity class' => 'RoomsRoomType',
    'controller class' => 'RoomsRoomTypeController',
    'base table' => 'rooms_type',
    'fieldable' => FALSE,
    'bundle of' => 'rooms_room',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'rooms_room_type_access',
    'module' => 'rooms_room',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/rooms/room_types',
      'file' => 'rooms_room_type.admin.inc',
      'controller class' => 'RoomsRoomTypeUIController',
    ),
  );

  return $return;
}


/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the room types via a hook to avoid a recursion
 * issue as loading the room types requires the entity info as well.
 *
 * @todo This needs to be improved
 */
function rooms_room_entity_info_alter(&$entity_info) {
  foreach (rooms_room_get_types() as $type => $info) {
    $entity_info['rooms_room']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/rooms/room_types/manage/%rooms_room_type',
        'real path' => 'admin/rooms/room_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer rooms'),
      ),
    );
  }
}
  

/**
 * Implements hook_permission().
 */
function rooms_room_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer room types' => array(
      'title' => t('Administer room types'),
      'description' => t('Create and delete fields for room types, and set their permissions.'),
    ),
    'administer rooms' => array(
      'title' => t('Administer rooms'),
      'description' => t('Edit and delete all rooms'),
    ),  
  );
  
  //Generate permissions per room 
  foreach (rooms_room_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name room" => array(
        'title' => t('%type_name: Edit any room', array('%type_name' => $type->label)),
      ),
      "view any $type_name room" => array(
        'title' => t('%type_name: View any room', array('%type_name' => $type->label)),
      ),
    );
  }
  return $permissions;  
}


/**
 * Determines whether the given user has access to a room.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $room
 *   Optionally a room or a room type to check access for. If nothing is
 *   given, access for all rooms is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function rooms_room_access($op, $room = NULL, $account = NULL) {
  if (user_access('administer rooms', $account)) {
    return TRUE;
  }
  if (isset($room) && $type_name = $room->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name room", $account)) {
      return TRUE;
    }
  }
  return FALSE;
}


/**
 * Access callback for the entity API.
 */
function rooms_room_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer room types', $account);
}


/**
 * Gets an array of all room types, keyed by the type name.
 *
 * @param $type_name
 *   If set, the type with the given name is returned.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return RoomsRoomType[]
 *   Depending whether $type isset, an array of room types or a single one.
 */
function rooms_room_get_types($type_name = NULL, $reset = FALSE) {
  // entity_load will get the Entity controller for our room entity and call the load
  // function of that object.
  $types = entity_load_multiple_by_name('rooms_room_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}


/**
 * Menu argument loader; Load a room type by string.
 *
 * @param $type
 *   The machine-readable name of a room type to load.
 * @return
 *   A room type array or FALSE if $type does not exist.
 */
function rooms_room_type_load($type, $reset = FALSE) {
  return rooms_room_get_types($type, $reset);
}


/**
 * Fetch a room object. Make sure that the wildcard you choose 
 * in the room entity definition fits the function name here.
 *
 * @param $room_id
 *   Integer specifying the room id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $room object or FALSE if it cannot be loaded.
 *
 * @see rooms_room_load_multiple()
 */
function rooms_room_load($room_id, $reset = FALSE) {
  $rooms = rooms_room_load_multiple(array($room_id), array(), $reset);
  return reset($rooms);
}


/**
 * Load multiple rooms based on certain conditions.
 *
 * @param $room_ids
 *   An array of room IDs.
 * @param $conditions
 *   An array of conditions to match against the {room} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of room objects, indexed by room_id.
 *
 * @see entity_load()
 * @see rooms_room_load()
 */
function rooms_room_load_multiple($room_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('rooms_room', $room_ids, $conditions, $reset);
}


/**
 * Deletes a room.
 */
function rooms_room_delete(RoomsRoom $room) {
  $room->delete();
}


/**
 * Delete multiple rooms.
 *
 * @param $room_ids
 *   An array of room IDs.
 */
function rooms_room_delete_multiple(array $room_ids) {
  entity_get_controller('rooms_room')->delete($room_ids);
}


/**
 * Create a room object.
 */
function rooms_room_create($values = array()) {
  return entity_get_controller('rooms_room')->create($values);
}


/**
 * Saves a room to the database.
 *
 * @param $room
 *   The room object.
 */
function rooms_room_save(RoomsRoom $room) {
  return $room->save();
}


/**
 * Saves a room type to the db.
 */
function rooms_room_type_save(RoomsRoomType $type) {
  $type->save();
}


/**
 * Deletes a room type from the db.
 */
function rooms_room_type_delete(RoomsRoomType $type) {
  $type->delete();
}


/**
 * URI callback for rooms
 */
function rooms_room_uri(RoomsRoom $room){
  return array(
    'path' => 'room/' . $room->room_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function rooms_room_page_title(RoomsRoom $room){
  return $room->name;
}


/**
 * Sets up content to show an individual room
 * @todo - get rid of drupal_set_title();
 */
function rooms_room_page_view($room, $view_mode = 'full') {    
  $controller = entity_get_controller('rooms_room');  
  $content = $controller->view(array($room->room_id => $room));
  drupal_set_title($room->name);
  return $content;
}


/**
 * Implements hook_views_api().
 */
function rooms_room_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'rooms_room') . '/views',
  );
}


/**
 * Implement hook_theme().
 */
function rooms_room_theme() {
  return array(
    'rooms_room_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'rooms_room.admin.inc',
    ),
    'room' => array(
      'render element' => 'elements',
      'template' => 'rooms_room',
    ),
   'rooms_room_extra_data' => array(
      'variables' => array('room_extra_data', 'room' => NULL),
      'template' => 'rooms_room-extra-data',
    ),
  );
}  


/**
 * Implements hook_menu_local_tasks_alter().
 */
function rooms_room_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/rooms/rooms/add' on 'admin/rooms/rooms'.
  if ($root_path == 'admin/rooms/rooms') {
    $item = menu_get_item('admin/rooms/rooms/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * The class used for room entities
 */
class RoomsRoom extends Entity {
  
  public function __construct($values = array()) {
    parent::__construct($values, 'rooms_room');
  }

  protected function defaultLabel() {
    return $this->name;
  }

  protected function defaultUri() {
    return array('path' => 'room/' . $this->room_id);
  }
  
  
}


/**
 * The class used for room type entities
 */
class RoomsRoomType extends Entity {
  
  public $type;
  public $label;
  
  public function __construct($values = array()) {
    parent::__construct($values, 'rooms_room_type');
  }
  
}


/**
 * The Controller for RoomsRoom entities
 */
class RoomsRoomController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a room - we first set up the values that are specific
   * to our room schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the room.
   *
   * @return
   *   A room object with all default fields initialized.
   */
  public function create(array $values = array()) {
    $room_type = rooms_room_type_load($values['type'], TRUE);
    $values['base_price'] = $room_type->data['base_price'];
    $values['sleeps'] = $room_type->data['sleeps'];

    // Add values that are specific to our Room
    $values += array( 
      'room_id' => '',
      'is_new' => TRUE,
      'title' => '',
      'created' => '',
      'changed' => '',
      'data' => array(),
    );
    
    $room = parent::create($values);
    return $room;
  }
  
  /**
   * Overriding the buldContent function to add entity specific fields
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $content = parent::buildContent($entity, $view_mode, $langcode, $content);
    $content['rooms_room_extra_data'] =  array(
      '#markup' => theme('rooms_room_extra_data', array('rooms_room_extra_data' => check_plain($entity->data['extra_data']), 'rooms_room' => $entity)),
    );

    return $content;
  }
  
}


/**
 * The Controller for Room entities
 */
class RoomsRoomTypeController extends EntityAPIControllerExportable {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }
  
   /**
   * Create a room type - we first set up the values that are specific
   * to our room type schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the room.
   *
   * @return
   *   A room type object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Room
    $values += array( 
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $room_type = parent::create($values);
    return $room_type;
  }

}