<?php

/**
 * @file
 * Manages availability for Bookable Units and displaying dates on the jquery FullCalendar
 * plugin
 */


define('ROOMS_AVAILABILITY_ADMIN_STYLE', 1);
define('ROOMS_AVAILABILITY_GENERIC_STYLE', 2);


/**
 * Implements hook_permission().
 */
function rooms_availability_permission() {
  $permissions = array(
    'manage booking unit availability' => array(
      'title' => t('Manage unit availability'),
      'description' => t('Allows users to manage availability settings for Rooms.'),
      'restrict access' => TRUE,
    ),
    'view anonymous availability information' => array(
      'title' => t('View anonymous availability information'),
      'description' => t('Allow users to view anonymous availability info (especially via availability reference field).'),
    ),
    'view named availability information' => array(
      'title' => t('View named availability information'),
      'description' => t('Allow users to view named availability info (especially via availability reference field).'),
    ),
    'view past availability information' => array(
      'title' => t('View past availability information'),
      'description' => t('Allow users to view availability info in the past (especially via availability reference field).'),
    ),
  );
  return $permissions;
}


/**
 * Implements hook_menu().
 */
function rooms_availability_menu() {
  $items = array();

  $items['admin/rooms/units/unit/%availability_unit/availability'] = array(
    'title' => 'Manage Availability',
    'page callback' => 'rooms_availability_page',
    'page arguments' => array(4, 6, 7),
    'access callback' => 'rooms_availability_admin_access',
    'access arguments' => array(4),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'weight' => '20',
  );

  $items['rooms/units/unit/%availability_unit/availability/json/%/%'] = array(
    'title' => 'Availability Event',
    'page callback' => 'rooms_availability_event',
    'page arguments' => array(3, 6, 7, 8, 9, 10, 11, 12),
    'access callback' => 'rooms_availability_access',
    'access arguments' => array(4),
    'type' => MENU_CALLBACK,
    'weight' => 30,
  );

  $items['admin/rooms/units/unit/%availability_unit/event'] = array(
    'title' => 'Event Management',
    'page callback' => 'rooms_availability_event_manager_page',
    'page arguments' => array(4),
    'access callback' => 'rooms_availability_access',
    'access arguments' => array(4),
    'type' => MENU_CALLBACK,
    'weight' => 30,
  );

  $items['admin/rooms/units/bulk_unit_management'] = array(
    'title' => 'Bulk availability management',
    'page callback' => 'rooms_availability_bulk_unit_management',
    'page arguments' => array(4, 5, 6),
    'access callback' => 'rooms_availability_access',
    'access arguments' => array(4),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  $items['admin/rooms/units/bulk_pricing_management'] = array(
    'title' => 'Bulk pricing management',
    'page callback' => 'rooms_availability_bulk_pricing_management',
    'page arguments' => array(4, 5, 6),
    'access callback' => 'rooms_bulk_pricing_access',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  $items['admin/rooms/select-all-pages-av'] = array(
    'title' => 'AJAX Select all availability pages callback',
    'type' => MENU_CALLBACK,
    'page callback' => 'rooms_availability_av_ajax_callback',
    'access arguments' => array('view named availability information'),
  );

  $items['admin/rooms/select-all-pages-pr'] = array(
    'title' => 'AJAX Select all pricing pages callback',
    'type' => MENU_CALLBACK,
    'page callback' => 'rooms_availability_pr_ajax_callback',
    'access arguments' => array('manage booking unit pricing'),
  );

  return $items;
}

function rooms_availability_av_ajax_callback() {
  if ($_POST['select-all'] == '1') {
    variable_set('ROOMS_SELECT_ALL_PAGES_AV', 'true');
  }
  else {
    variable_set('ROOMS_SELECT_ALL_PAGES_AV', 'false');
  }
}

function rooms_availability_pr_ajax_callback() {
  if ($_POST['select-all'] == '1') {
    variable_set('ROOMS_SELECT_ALL_PAGES_PR', 'true');
  }
  else {
    variable_set('ROOMS_SELECT_ALL_PAGES_PR', 'false');
  }
}

/**
 * Form for the Bulk Availability Management. Could receive date params for the
 * interested interval to edit.
 */
function rooms_availability_bulk_unit_management($year = '', $month = '', $type = 'all', $action = '', $start = '', $end = '') {
  // Load FullCalendar
  rooms_fullcalendar_loaded();

  // modal includes and style
  rooms_availability_modal_style();

  // If year is not set then give it the current date
  $year = ($year != '' && is_numeric($year)) ? $year : date('Y', time());
  $month = ($month != '' && is_numeric($month)) ? $month : date('n', time());
  $type = ($type == '') ? 'all' : $type;

  // It's not a valid unit type
  if (rooms_unit_get_types($type) == FALSE) {
    $type = 'all';
  }

  // It's not a valid month
  if ($month < 1 || $month > 12) {
    $month = 1;
  }

  $page = 0;
  if (isset($_GET['page'])) {
    $page = check_plain($_GET['page']);
    if ($page < 0) $page = 0;
  }

  $query = db_select('rooms_units', 'n')->fields('n', array('unit_id', 'name'));
  $query2 = db_select('rooms_units', 'n')->fields('n', array('unit_id', 'name'));
  if ($type != 'all') {
    $query->condition('type', $type, '=');
    $query2->condition('type', $type, '=');
  }
  $query->range($page * 20, 20);
  $rooms_units = $query->execute()->fetchAll();

  $n_total_row = $query2->countQuery()->execute()->fetchField();

  $rooms_id = array();
  foreach ($rooms_units as $value) {
    $rooms_id[] = $value->unit_id;
  }

  // Add pager
  pager_default_initialize($n_total_row, 20);

  // Return the full render array.
  return array(
    drupal_get_form('rooms_availability_filter_month_form', $month, $year),
    drupal_get_form('rooms_availability_update_status_form', $month, $year, $type, $rooms_units),
    array(
      '#theme' => 'pager',
      '#quantity' => $n_total_row,
      '#tags' => array(t('« first'), t('‹ previous'), '', t('next ›'), t('last »'))
    ),
    '#attached' => array(
      'css' => array(drupal_get_path('module', 'rooms_availability') . '/css/rooms_availability.css'),
      'js' => array(
        drupal_get_path('module', 'rooms_availability') . '/js/rooms_unit_management.js',
        array(
          'data' => array(
            'roomsUnitManagement' => array(
              'roomsNumber' => count($rooms_units),
              'currentMonth' => $month,
              'currentYear' => $year,
              'roomsId' => $rooms_id
            ),
          ),
          'type' => 'setting',
        )
      )
    )
  );
}

/**
 * Page callback for Bulk Pricing Management.
 */
function rooms_availability_bulk_pricing_management($year = '', $month = '', $type = 'all', $action = '', $start = '', $end = '') {
  // Load FullCalendar and relevant js/css
  rooms_fullcalendar_loaded();

  // If year is not set then give it the current date
  $year = ($year == '') ? date('Y', time()) : $year;
  $month = ($month == '') ? date('n', time()) : $month;
  $type = ($type == '') ? 'all' : $type;

  // It's not a valid unit type
  if (rooms_unit_get_types($type) == FALSE) {
    $type = 'all';
  }

  // It's not a valid month or not valid year
  $year_options = range(date('Y', time()) - 2, date('Y', time()) + 5);
  if ($month < 1 || $month > 12 || !in_array($year, $year_options)) {
    $year = date('Y', time());
    $month = date('n', time());
  }

  $page = 0;
  if (isset($_GET['page'])) {
    $page = check_plain($_GET['page']);
    if ($page < 0) $page = 0;
  }

  $query = db_select('rooms_units', 'n')->fields('n', array('unit_id', 'name'));
  $query2 = db_select('rooms_units', 'n')->fields('n', array('unit_id', 'name'));
  if ($type != 'all') {
    $query->condition('type', $type, '=');
    $query2->condition('type', $type, '=');
  }
  $query->range($page * 20, 20);
  $rooms_units = $query->execute()->fetchAll();

  $n_total_row = $query2->countQuery()->execute()->fetchField();

  $rooms_id = array();
  foreach ($rooms_units as $value) {
    $rooms_id[] = $value->unit_id;
  }

  // Add pager
  pager_default_initialize($n_total_row, 20);

  // Return the full render array.
  return array(
    drupal_get_form('rooms_availability_filter_month_form', $month, $year),
    drupal_get_form('rooms_availability_pricing_update_form', $month, $year, $type, $rooms_units),
    array(
      '#theme' => 'pager',
      '#quantity' => $n_total_row,
      '#tags' => array(t('« first'), t('‹ previous'), '', t('next ›'), t('last »'))
    ),
    '#attached' => array(
      'css' => array(drupal_get_path('module', 'rooms_availability') . '/css/rooms_availability.css'),
      'js' => array(
        drupal_get_path('module', 'rooms_availability') . '/js/rooms_pricing_management.js',
        array(
          'data' => array(
            'roomsUnitManagement' => array(
              'roomsNumber' => count($rooms_units),
              'currentMonth' => $month,
              'currentYear' => $year,
              'roomsId' => $rooms_id
            ),
          ),
          'type' => 'setting',
        )
      )
    )
  );
}


function rooms_availability_filter_month_form($form, &$form_state, $month, $year) {

  $form['#attributes']['class'][] = 'rooms-management-form rooms-filter-month-form';

  $month_options = array(
    1 => t('January'),
    2 => t('February'),
    3 => t('March'),
    4 => t('April'),
    5 => t('May'),
    6 => t('June'),
    7 => t('July'),
    8 => t('August'),
    9 => t('September'),
    10 => t('October'),
    11 => t('November'),
    12 => t('December'),
  );

  $form['rooms_availability_filter_month']['month'] = array(
    '#title' => t('Month'),
    '#type' => 'select',
    '#options' => $month_options,
    '#default_value' => $month,
  );

  $year_options = range(date('Y', time()) - 2, date('Y', time()) + 5);

  $form['rooms_availability_filter_month']['year'] = array(
    '#title' => t('Year'),
    '#type' => 'select',
    '#options' => $year_options,
    '#default_value' => $year - date('Y', time()) + 2,
  );

  $query = db_select('rooms_unit_type', 'n')->fields('n', array('type', 'label'));
  $unit_type = $query->execute()->fetchAll();

  $type_options['all'] = t('All types');
  foreach ($unit_type as $unit) {
    $type_options[$unit->type] = $unit->label;
  }

  $form['rooms_availability_filter_month']['type'] = array(
    '#title' => t('Type'),
    '#type' => 'select',
    '#options' => $type_options,
    '#default_value' => (arg(6) == '') ? 'all' : arg(6),
  );

  $form['rooms_availability_filter_month']['actions'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('form-actions')),
    '#weight' => 400,
  );

  $form['rooms_availability_filter_month']['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Filter'),
  );

  hide($form['rooms_availability_filter_month']['actions']['submit']);

  return $form;
}


function rooms_availability_filter_month_form_submit(&$form, &$form_state) {
  global $base_url;

  if (arg(3) == 'bulk_pricing_management') {
    variable_set('ROOMS_SELECT_ALL_PAGES_PR', 'false');
  }
  elseif (arg(3) == 'bulk_unit_management') {
    variable_set('ROOMS_SELECT_ALL_PAGES_AV', 'false');
  }

  $year = $form_state['values']['year'] + date('Y', time()) - 2;
  $month = $form_state['values']['month'];
  $type = $form_state['values']['type'];

  $address = $base_url . '/admin/rooms/units/' . arg(3) . '/' . $year . '/' . $month;
  if ($type != 'all') {
    $address .= '/' . $type;
  }

  if (arg(7) != '') {
    if ($type == 'all') $address .= '/all/' . arg(7);
    else $address .= $type . arg(7);
  }

  $form_state['redirect'] = $address;
}

/**
 * Form to manage the room units pricing.
 *
 * @see rooms_availability_bulk_pricing_management()
 */
function rooms_availability_pricing_update_form($form, &$form_state, $month, $year, $type, $rooms_units) {

  $form['#attributes']['class'][] = 'rooms-management-form rooms-bulk-pricing-form';

  $form['rooms_pricing_update'] = array(
    '#type' => 'fieldset',
    '#title' => t('Update Pricing'),
    '#description' => t('Apply a pricing adjustment in bulk to the units selected below for the specified date range.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['rooms_pricing_update']['curr_month'] = array(
    '#type' => 'hidden',
    '#value' => $month,
  );

  $form['rooms_pricing_update']['curr_year'] = array(
    '#type' => 'hidden',
    '#value' => $year,
  );

  $form['rooms_pricing_update']['curr_type'] = array(
    '#type' => 'hidden',
    '#value' => $type,
  );

  $form['rooms_pricing_update']['rooms_date_range'] = rooms_availability_date_range_fields($year, $month);

  $form['rooms_pricing_update']['day_options'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Days of the Week applicable'),
    '#options' => array(
      '1' => t('Sun'),
      '2' => t('Mon'),
      '3' => t('Tue'),
      '4' => t('Wed'),
      '5' => t('Thu'),
      '6' => t('Fri'),
      '7' => t('Sat'),
    ),
  );

  $form['rooms_pricing_update']['op'] = array(
    '#type' => 'fieldset',
  );

  $price_options = rooms_price_options_options();
  $form['rooms_pricing_update']['op']['operation'] = array(
    '#type' => 'select',
    '#title' => t('Operation'),
    '#options' => $price_options,
    '#default_value' =>  'replace',
  );

  $form['rooms_pricing_update']['op']['amount'] = array(
    '#type' => 'textfield',
    '#title' => t('Amount'),
    '#default_value' => '',
    '#size' => '5',
    '#description' => t('Amount to apply for rule'),
    '#maxlength' => 10,
    '#required' => TRUE,
  );

  $form['rooms_pricing_update']['actions'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('form-actions')),
    '#weight' => 400,
  );

  $form['rooms_pricing_update']['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update Unit Pricing'),
  );

  $form['#validate'][] = 'rooms_availability_pricing_update_form_validate';
  $form['#validate'][] = 'rooms_form_start_end_dates_validate';

  $form['rooms_data'] = array(
    '#prefix' => '<table class="rooms-month-manager">',
    '#type' => 'container',
    '#suffix' => '</tbody></table>',
  );

  if (count($rooms_units) > 0) {
    $date = new DateTime();
    $date->setDate($year, $month, '01');
    $form['rooms_data']['select-all'] = array(
      '#type' => 'select',
      '#prefix' => '<thead><tr><th class="unit-bulk-select">',
      '#options' => array(t('- Select -'), t('All (this page)'), t('All (all pages)'), t('None')),
      '#suffix' => '</th><th class="month-name"><div class="fc-header-title"><h2>' . format_date($date->getTimestamp(), 'custom', 'F Y') . '</h2></div></th></tr></thead><tbody>',
    );

    if (variable_get('ROOMS_SELECT_ALL_PAGES_PR') == 'true') {
      $form['rooms_data']['select-all']['#default_value'] = '2';
    }
  }

  foreach ($rooms_units as $key => $value) {
    $form['rooms_data']['rooms-'.$value->unit_id] = array(
      '#type' => 'checkbox',
      '#title' => $value->name,
      '#prefix' => '<tr><th class="unit-name">',
      '#suffix' => '</th><td class="unit-days"><div id="calendar' . $key . '"></div></td></tr>',
    );

    if (variable_get('ROOMS_SELECT_ALL_PAGES_PR') == 'true') {
      $form['rooms_data']['rooms-' . $value->unit_id]['#default_value'] = '1';
    }
  }

  return $form;
}

/**
 * Validate callback for rooms_availability_pricing_update_form form.
 */
function rooms_availability_pricing_update_form_validate(&$form, &$form_state) {
  // Make sure amount entered is numeric
  if (!empty($form_state['values']['amount']) && !is_numeric($form_state['values']['amount'])) {
    form_set_error('amount', t('%name: you must enter a numeric value for the price.', array('%name' => t('Amount'))));
  }
  // validate that a rooms is selected
  _rooms_availability_select_rooms_validation($form_state);
}

/**
 * Submit callback for rooms_availability_pricing_update_form form.
 */
function rooms_availability_pricing_update_form_submit(&$form, &$form_state) {
  list($start_date, $end_date) = rooms_form_input_get_start_end_dates($form_state);
  $type = $form_state['values']['curr_type'];
  $operation = $form_state['values']['operation'];
  $amount = $form_state['values']['amount'];
  $days = array_filter($form_state['values']['day_options']);

  if (variable_get('ROOMS_SELECT_ALL_PAGES_PR') == 'true') {
    $query = db_select('rooms_units', 'n')->fields('n', array('unit_id', 'name'));
    if ($type != 'all') {
      $query->condition('type', $type , '=');
    }
    $rooms_units = $query->execute()->fetchAll();

    foreach ($rooms_units as $room) {
      $unit_id = $room->unit_id ;

      if (!empty($days)) {

        // Get all the pricing events for the date range
        $rc = new UnitPricingCalendar($unit_id);
        $events = $rc->calculatePricingEvents($unit_id, $amount, $start_date, $end_date, $operation, $days);

        $rc->updateCalendar($events);

      }
      else {

        // Get all the pricing events for the date range
        $rc = new UnitPricingCalendar($unit_id);
        $pe = new PricingEvent($unit_id, $amount, $start_date, $end_date, $operation);
        $events = array($pe);

        $rc->updateCalendar($events);

      }
    }
  }
  else {
    foreach ($form_state['values'] as $key => $value) {
      if (strpos($key, 'rooms-') === 0 && $value == '1') {
        $unit_id = str_replace('rooms-', '', $key);

        if (!empty($days)) {

          // Get all the pricing events for the date range
          $rc = new UnitPricingCalendar($unit_id);
          $events = $rc->calculatePricingEvents($unit_id, $amount, $start_date, $end_date, $operation, $days);

          $rc->updateCalendar($events);

        }
        else {

          // Get all the pricing events for the date range
          $rc = new UnitPricingCalendar($unit_id);
          $pe = new PricingEvent($unit_id, $amount, $start_date, $end_date, $operation);
          $events = array($pe);

          $rc->updateCalendar($events);

        }
      }
    }
  }

  variable_set('ROOMS_SELECT_ALL_PAGES_PR', 'false');
}

/**
 * Form to manage the availability for specific month.
 *
 * @see rooms_availability_bulk_unit_management()
 */
function rooms_availability_update_status_form($form, &$form_state, $month, $year, $type, $rooms_units) {

  $form['#attributes']['class'][] = 'rooms-management-form rooms-bulk-availability-form';

  $form['rooms_availability_update'] = array(
    '#type' => 'fieldset',
    '#title' => t('Update Availability'),
    '#description' => t('Change the availability status of the units selected below for the specified date range.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['rooms_update_availability']['curr_month'] = array(
    '#type' => 'hidden',
    '#value' => $month,
  );

  $form['rooms_update_availability']['curr_year'] = array(
    '#type' => 'hidden',
    '#value' => $year,
  );

  $form['rooms_update_availability']['curr_type'] = array(
    '#type' => 'hidden',
    '#value' => $type,
  );

  $form['rooms_availability_update']['rooms_date_range'] = rooms_availability_date_range_fields($year, $month);

  $state_options = rooms_unit_state_options();
  $form['rooms_availability_update']['change_event_status'] = array(
    '#title' => t('Bookable Unit State'),
    '#type' => 'select',
    '#options' => $state_options,
    '#empty_option' => t('- Select -'),
  );

  $form['rooms_availability_update']['actions'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('form-actions')),
    '#weight' => 400,
  );

  $form['rooms_availability_update']['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update Unit Availability'),
  );

  $form['#validate'][] = 'rooms_form_start_end_dates_validate';
  $form['#validate'][] = 'rooms_availability_update_status_form_validate';

  $form['rooms_data'] = array(
    '#prefix' => '<table class="rooms-month-manager">',
    '#type' => 'container',
    '#suffix' => '</tbody></table>',
  );

  if (count($rooms_units) > 0) {
    $date = new DateTime();
    $date->setDate($year, $month, '01');
    $form['rooms_data']['select-all'] = array(
      '#type' => 'select',
      '#prefix' => '<thead><tr><th class="unit-bulk-select">',
      '#options' => array(t('- Select -'), t('All (this page)'), t('All (all pages)'), t('None')),
      '#suffix' => '</th><th class="month-name"><div class="fc-header-title"><h2>' . format_date($date->getTimestamp(), 'custom', 'F Y') . '</h2></div></th></tr></thead><tbody>',
    );

    if (variable_get('ROOMS_SELECT_ALL_PAGES_AV') == 'true') {
      $form['rooms_data']['select-all']['#default_value'] = '2';
    }
  }

  foreach ($rooms_units as $key => $value) {
    $form['rooms_data']['rooms-' . $value->unit_id] = array(
      '#type' => 'checkbox',
      '#title' => $value->name,
      '#prefix' => '<tr><th class="unit-name">',
      '#suffix' => '</th><td  class="unit-days"><div id="calendar' . $key . '"></div></td></tr>',
    );

    if (variable_get('ROOMS_SELECT_ALL_PAGES_AV') == 'true') {
      $form['rooms_data']['rooms-' . $value->unit_id]['#default_value'] = '1';
    }
  }

  return $form;
}

/**
 * Validate callback for rooms_availability_update_status_form form.
 */
function rooms_availability_update_status_form_validate(&$form, &$form_state) {
  if (!$form_state['values']['change_event_status']) {
    form_set_error('change_event_status', t('Select a valid status.'));
  }
  // validate that a rooms is selected
  _rooms_availability_select_rooms_validation($form_state);
}

function rooms_availability_update_status_form_submit(&$form, &$form_state) {
  list($start_date, $end_date) = rooms_form_input_get_start_end_dates($form_state);
  $type = $form_state['values']['curr_type'];
  $event_id = $form_state['values']['change_event_status'];

  if (variable_get('ROOMS_SELECT_ALL_PAGES_AV') == 'true') {
    $query = db_select('rooms_units', 'n')->fields('n', array('unit_id', 'name'));
    if ($type != 'all') {
      $query->condition('type', $type , '=');
    }
    $rooms_units = $query->execute()->fetchAll();

    foreach ($rooms_units as $room) {
      $unit_id = $room->unit_id ;

      // Create a new Booking Event
      $be = new BookingEvent($unit_id, $event_id, $start_date, $end_date);
      $events = array($be);
      $rc = new UnitCalendar($unit_id);
      $response = $rc->updateCalendar($events);
      if ($response[$event_id] == ROOMS_BLOCKED) {
        drupal_set_message($room->name . ' - ' . t('Could not update calendar because a locked event is blocking the update - you need to unlock any locked events in that period.'), 'warning');
      }
      elseif ($response[$event_id] == ROOMS_UPDATED) {
        drupal_set_message($room->name . ' - ' . t('Calendar Updated'));
      }
    }
  }
  else {
    foreach ($form_state['values'] as $key => $value) {
      if (strpos($key, 'rooms-') === 0 && $value == '1') {
        $unit_id = str_replace('rooms-', '', $key);

        // Create a new Booking Event
        $be = new BookingEvent($unit_id, $event_id, $start_date, $end_date);
        $events = array($be);
        $rc = new UnitCalendar($unit_id);
        $response = $rc->updateCalendar($events);
        if ($response[$event_id] == ROOMS_BLOCKED) {
          drupal_set_message($form_state['complete form']['rooms_data'][$key]['#title'] . ' - ' . t('Could not update calendar because a locked event is blocking the update - you need to unlock any locked events in that period.'), 'warning');
        }
        elseif ($response[$event_id] == ROOMS_UPDATED) {
          drupal_set_message($form_state['complete form']['rooms_data'][$key]['#title'] . ' - ' . t('Calendar Updated'));
        }
      }
    }
  }

  variable_set('ROOMS_SELECT_ALL_PAGES_AV', 'false');
}


/**
 * Menu load for units - calls the actuall rooms_unit_load implemented in rooms_unit.module
 */
function availability_unit_load($unit_id) {
  $unit_ids = explode(',', $unit_id);

  // If there is just a single id lets return that directly (this is for backwards compatibility
  // to avoid having to change all fucntions directly)
  if (count($unit_ids) == 1) {
    $units = rooms_unit_load($unit_ids[0]);
    return $units;
  }
  else {

    $units = array();

    foreach ($unit_ids as $unit) {
      $units[] = rooms_unit_load($unit);
    }
    return $units;
  }
}



/**
 * Unit availability admin access callback
 */
function rooms_availability_admin_access($rooms_unit) {
  if (user_access('manage booking unit availability')) {
    return TRUE;
  }
  return FALSE;
}


/**
 * Unit availability access callback
 */
function rooms_availability_access($rooms_unit) {
  if (user_access('view anonymous availability information') || user_access('view named availability information')) {
    return TRUE;
  }
  return FALSE;
}


/**
 * Unit availability access callback
 */
function rooms_bulk_pricing_access() {
  if (user_access('manage booking unit pricing')) {
    return TRUE;
  }
  return FALSE;
}


/**
 * Callback for admin/rooms/units/unit/%unit/availability - builds availability
 * page by adding calendar and pulling events from availability table.
 *
 */
function rooms_availability_page(RoomsUnit $rooms_unit, $year='', $month='') {
  // Set the page title.
  drupal_set_title(t('Edit @unit_name Availability', array('@unit_name' => $rooms_unit->name)));

  // Add styles.
  rooms_availability_modal_style();

  // Get the current page's URL, striped of the year and month args.
  // This allows us to place this page anywhere, including at
  // unit/%/availability  or  admin/rooms/units/unit/%/availability
  list($url) = explode('/' . $year . '/' . $month, current_path());

  return array(
    '#theme' => 'rooms_three_month_calendar',
    '#url' => $url,
    '#form' => drupal_get_form('update_availability_calendar_form', $rooms_unit->unit_id, $year, $month),
    '#year' => $year,
    '#month' => $month,
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'rooms_availability') . '/css/rooms_availability.css',
      ),
      'js' => array(
        drupal_get_path('module', 'rooms_availability') . '/js/rooms_availability.js',
        array(
          'data' => array('roomsAvailability' => array('roomID' => $rooms_unit->unit_id)),
          'type' =>'setting',
        ),
      ),
    ),
  );
}

/**
 * Default implementation of hook_preprocess_rooms_three_month_calendar().
 *
 * Here we setup the three-month calendar based on a specified year,
 * month, and url.
 */
function rooms_availability_preprocess_rooms_three_month_calendar(&$vars) {

  // Load FullCalendar
  rooms_fullcalendar_loaded();

  // Add css styles for three-month-calendar.
  drupal_add_css(drupal_get_path('module', 'rooms_availability') . '/css/rooms_three_month_calendar.css');
  drupal_add_css(drupal_get_path('module', 'rooms_availability') . '/css/fullcalendar.theme.css');

  // If dates are not provided then use the current date.
  $year = (empty($vars['year'])) ? date('Y', time()) : check_plain($vars['year']);
  $month = (empty($vars['month'])) ? date('n', time()) : check_plain($vars['month']);

  // Inject settings in javascript that will be used to setup the three months
  // display.
  drupal_add_js(array('roomsCalendar' => array('currentMonth' => $month)), 'setting');
  drupal_add_js(array('roomsCalendar' => array('currentYear' => $year)), 'setting');

  // Calculate forward and back dates for the 3-month view calendar.
  $date1 = new DateTime("$year-$month-1");
  $date2 = new DateTime("$year-$month-1");
  $date_current = new DateTime("now");

  $forward = $date1->add(new DateInterval('P3M'));
  $backward = $date2->sub(new DateInterval('P3M'));

  // Create the links based off the url variable passed in.
  if (!isset($vars['url'])) {
    $vars['url'] = '';
  }

  $forward_path = $vars['url'] . '/' . $forward->format('Y') . '/' . $forward->format('n');
  $backward_path = $vars['url'] . '/' . $backward->format('Y') . '/' . $backward->format('n');
  $current_path = $vars['url'] . '/' . $date_current->format('Y') . '/' . $date_current->format('n');

  $vars['forward_link'] = l(t('Forward'), $forward_path);
  $vars['backward_link'] = l(t('Back'), $backward_path);
  $vars['current_link'] = l(t('Current'), $current_path);
}


/**
 * A basic form that allows us to update the state of the calendar
 */
function update_availability_calendar_form($form, &$form_state, $unit_id, $year, $month) {

  $form['#attributes']['class'][] = 'rooms-management-form rooms-availability-calendar-form';

  $form['rooms_update_availability'] = array(
    '#type' => 'fieldset',
    '#title' => t('Update Unit Availability'),
    '#description' => t('Change the availability status for a specified date range.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['rooms_update_availability']['unit_id'] = array(
    '#type' => 'hidden',
    '#value' => $unit_id,
  );

  $form['rooms_update_availability']['rooms_date_range'] = rooms_date_range_fields();
  // Unset a js setting
  drupal_add_js(array('rooms' => array('roomsBookingStartDay' => 0)), 'setting');

  $state_options = rooms_unit_state_options();
  $form['rooms_update_availability']['unit_state'] = array(
    '#type' => 'select',
    '#title' => t('Change status to'),
    '#options' => $state_options,
  );

  $form['rooms_update_availability']['actions'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('form-actions')),
    '#weight' => 400,
  );

  // We add the form's #submit array to this button along with the actual submit
  // handler to preserve any submit handlers added by a form callback_wrapper.
  $submit = array();

  if (!empty($form['rooms_update_availability']['#submit'])) {
    $submit += $form['rooms_update_availability']['#submit'];
  }

  $form['rooms_update_availability']['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update Availability'),
    '#submit' => $submit + array('update_availability_calendar_form_submit'),
  );

  // We append the validate handler to #validate in case a form callback_wrapper
  // is used to add validate handlers earlier.
  $form['#validate'][] = 'rooms_form_start_end_dates_validate';

  return $form;
}


/**
 *@todo Need to figure out what to do when we cancel an existing booking
 */
function update_availability_calendar_form_submit(&$form, &$form_state) {
  list($start_date, $end_date) = rooms_form_input_get_start_end_dates($form_state);
  $event_id = $form_state['values']['unit_state'];
  $unit_id = $form_state['values']['unit_id'];

  // Create a new Booking Event
  $be = new BookingEvent($unit_id, $event_id, $start_date, $end_date);
  $events = array($be);
  $rc = new UnitCalendar($unit_id);
  $response = $rc->updateCalendar($events);
  if ($response[$event_id] == ROOMS_BLOCKED) {
    drupal_set_message(t('Could not update calendar because a locked event is blocking the update - you need to unlock any locked events in that period.'), 'warning');
  }
  elseif ($response[$event_id] == ROOMS_UPDATED) {
    drupal_set_message(t('Calendar Updated'));
  }
}



/**
 * Creates the necessary json for the date range provided - needs at least start year and month at which point it will
 * return the entire month.
 */
function rooms_availability_event($units, $start_year = '', $start_month = '', $start_day = '', $end_year = '', $end_month = '', $end_day = '', $event_style = ROOMS_AVAILABILITY_ADMIN_STYLE) {

  // Check if units is array and if not place in array
  if (!is_array($units)) {
    $units = array($units);
  }
  $start_year = (int)$start_year;
  $start_month = (int)$start_month;
  $start_day = (int)$start_day;

  $end_year = (int)$end_year;
  $end_month = (int)$end_month;
  $end_day = (int)$end_day;

  if (is_numeric($event_style)) $event_style = (int)$event_style;
  else $event_style = (int)ROOMS_AVAILABILITY_ADMIN_STYLE;

  // If user don't have 'view named availability information' permission
  if (!user_access('view named availability information') && !user_access('manage booking unit availability')
          && $event_style == ROOMS_AVAILABILITY_ADMIN_STYLE) {
    $event_style = (int)ROOMS_AVAILABILITY_GENERIC_STYLE;
  }
  // If user don't have 'view anonymous availability information' permission
  if (!user_access('view anonymous availability information')  && !user_access('manage booking unit availability')
          && $event_style == ROOMS_AVAILABILITY_GENERIC_STYLE) {
    echo drupal_json_encode(array());
  }

  if (!user_access('view past availability information')) {
    $start_day = date('j');
    $start_month = date('n');
    $start_year = date('Y');
  }

  $eom = rooms_end_of_month_dates($start_year);

  if (($start_year == 0) || ($start_month == 0)) {
    echo drupal_json_encode('missing basic info');
    return;
  }
  elseif ($start_day == 0) {
    $start_date = new DateTime("$start_year-$start_month-1");
    $end_day = $eom[$start_month];
    $end_date = new DateTime("$start_year-$start_month-$end_day");
  }
  elseif ($start_day != 0 && $end_year == 0) {
    $start_date = new DateTime("$start_year-$start_month-$start_day");
    $end_date = new DateTime("$start_year-$start_month-15");
    $end_date->add(new DateInterval('P1M'));
    $end_year = $end_date->format('Y');
    $end_month = $end_date->format('n');
    $end_day = $eom[$end_date->format('n')];
    $end_date = new DateTime("$end_year-$end_month-$end_day");
  }
  else {
    $start_date = new DateTime("$start_year-$start_month-$start_day");
    $end_date = new DateTime("$end_year-$end_month-$end_day");
  }

  $json_events  = array();
  foreach ($units as $unit) {
    $rc = new UnitCalendar($unit->unit_id, $unit->default_state);

    $events = $rc->getEvents($start_date, $end_date);

    foreach ($events as $event) {
      $json_events[] = $event->formatJson($event_style, $unit->name);
    }
  }

  echo drupal_json_encode($json_events);
}


/**
 * The EventManager page shows when clicking on an event in the availability
 * calendar - will allow a user to manipulate that event.
 */
function rooms_availability_event_manager_page($unit, $event_id = NULL, $start_date = 0, $end_date = 0) {
  // include modal library
  ctools_include('modal');

  // If any info missing we cannot load the event.
  if ($event_id == NULL || $start_date == 0 || $end_date == 0) {
    $output[] = ctools_modal_command_dismiss();
    drupal_set_message(t('Unable to load event.'), 'error');
  }

  // Basic check to avoid damage from dirty input.
  $event_id = check_plain($event_id);
  $start_date = check_plain($start_date);
  $end_date = check_plain($end_date);

  // Process start and end date.
  $sd = new DateTime();
  $sd->setTimezone(new DateTimeZone('UTC'))->setTimestamp($start_date);

  $ed = new DateTime();
  $ed->setTimezone(new DateTimeZone('UTC'))->setTimestamp($end_date);

  $booked = FALSE;
  if ($event_id > 10 || $event_id < -10) {
    $booked = TRUE;
  }

  if ($booked) {
    $booking_id = rooms_availability_return_id($event_id);
    $booking = rooms_booking_load($booking_id);
    // For existing bookings allow to edit in the modal.
    module_load_include('inc', 'rooms_booking', 'rooms_booking.admin');
    $form_state = array(
      'title' => t('Edit booking'),
      'ajax' => TRUE,
      'build_info' => array(
        'args' => array($booking),
        'files' => array(
          'rooms_booking_admin' => array(
            'module' => 'rooms_booking',
            'name' => 'rooms_booking.admin',
            'type' => 'inc',
          ),
        ),
      ),
    );
    // Wrap the form via ctools modal.
    $output = ctools_modal_form_wrapper('rooms_booking_edit_form', $form_state);
    if ($form_state['executed']) {
      $output = array(ctools_modal_command_dismiss());
    }
    print ajax_render($output);
    exit();
  }

  // If the event is blocked, show an error message.
  $uc = new UnitCalendar($unit->unit_id);
  $mock_event = new BookingEvent($unit->unit_id, NULL, $sd, $ed);
  if ($uc->eventBlocked($mock_event)) {
    drupal_set_message(t('You can not update calendar because a locked event is blocking the update. You need to unlock any locked events in that period.'), 'warning');
    $output = theme('status_messages');
    ctools_modal_render(t('Event Management'), $output);
    return;
  }

  ctools_modal_render(t('Event Management'), drupal_get_form('rooms_availability_event_manager_form', $unit, $event_id, $sd, $ed));
}

/**
 * Define modal JS style and dependencies
 */
function rooms_availability_modal_style() {
  // include libraries
  ctools_include('modal');
  ctools_include('ajax');
  ctools_modal_add_js();

  // styles to use for the modal
  $modal_style = array(
    'rooms-modal-style' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 400,
        'height' => 400,
        'addWidth' => 0,
        'addHeight' => 0,
      ),
      'modalOptions' => array(
        'opacity' => .0,
        'background-color' => '#000',
      ),
      'animation' => 'fadeIn',
    ),
  );

  // add the ctool modal configuration to settings
  drupal_add_js($modal_style, 'setting');

  // add the ctools modal stylesheet.
  drupal_add_css(drupal_get_path('module', 'rooms') . '/css/rooms_modal.css');
}


/**
 * The Event Manager Form - will eventually change based on the type of event we are manipulating
 */
function rooms_availability_event_manager_form($form, $form_state, $unit, $event_id, $start_date, $end_date) {
  $form = array();
  $new_event_id = $event_id;

  if (isset($form_state['values']['change_event_status'])) {
    $new_event_id = $form_state['values']['change_event_status'];
  }

  $state_options = rooms_unit_state_options();

  $form['#attributes']['class'][] = 'rooms-management-form rooms-event-form';

  // This entire form element will be replaced whenever 'changethis' is updated.
  $form['#prefix'] = '<div id="replace_textfield_div">';
  $form['#suffix'] = '</div>';

  $form['unit_id'] = array(
    '#type' => 'hidden',
    '#value' => $unit->unit_id,
  );

  $form['event_id'] = array(
    '#type' => 'hidden',
    '#value' => $event_id,
  );

  $form['rooms_start_date'] = array(
    '#type' => 'hidden',
    '#value' => $start_date,
  );

  $form['rooms_end_date'] = array(
    '#type' => 'hidden',
    '#value' => $end_date,
  );

  if ($event_id == -2) {
    $form['event_title'] = array(
      '#prefix' => '<h2>',
      '#markup' => check_plain($unit->name),
      '#suffix' => '</h2>'
    );
  }
  else {
    $form['event_title'] = array(
      '#prefix' => '<h2>',
      '#markup' => t('@unit_name is @status', array('@unit_name' => $unit->name, '@status' => $state_options[$new_event_id])),
      '#suffix' => '</h2>'
    );
  }

  $date_format = variable_get('rooms_date_format', 'd-m-Y');
  $form['event_details'] = array(
    '#prefix' => '<div class="event-details">',
    '#markup' => t('Duration: @startdate to @enddate', array('@startdate' => $start_date->format($date_format), '@enddate' => $end_date->format($date_format))),
    '#suffix' => '</div>'
  );

  unset($state_options[$new_event_id]);

  $form['change_event_status'] = array(
    '#title' => t('Change the state for this event to:') . ' ',
    '#type' => 'select',
    '#options' => $state_options,
    '#ajax' => array(
      'callback' => 'rooms_availability_ajax_event_status_change',
      'wrapper' => 'replace_textfield_div',
    ),
    '#empty_option' => t('- Select -'),
  );

  if (module_exists('rooms_booking') && $new_event_id != 89) {
    $booking_types = rooms_booking_get_types();

    foreach ($booking_types as $type) {
      $form['order']['order_link'][$type->type] = array(
        '#type' => 'markup',
        '#markup' => '<div>' . l(t('Create @booking_type', array('@booking_type' => $type->label)), 'admin/rooms/bookings/add/' . $type->type, array('query' => array('startdate' => $start_date->getTimestamp(), 'enddate' => $end_date->getTimestamp(), 'unitid' => $unit->unit_id))) . '</div>',
      );
    }
  }

  return $form;
}


/**
 * The callback for the change_event_status widget of the event manager form
 */
function rooms_availability_ajax_event_status_change($form, $form_state) {
  $start_date = $form_state['values']['rooms_start_date'];
  $end_date = $form_state['values']['rooms_end_date'];
  $unit_id = $form_state['values']['unit_id'];
  $event_id = $form_state['values']['event_id'];
  $new_event_id = $form_state['values']['change_event_status'];

  // If we have a new event id go ahead and update event
  if (($event_id != $new_event_id) && $new_event_id != -1) {
    $event = new BookingEvent($unit_id, $new_event_id, $start_date, $end_date);
    $uc = new UnitCalendar($unit_id);
    $responses = $uc->updateCalendar(array($event));

    $state_options = rooms_unit_state_options();
    if ($event_id >= -1) {
      $form['form_wrapper_bottom']['#markup'] = t('Updated event from <strong>@old_status</strong> to <strong>@new_status</strong>.', array('@old_status' => $state_options[$event_id], '@new_status' => $state_options[$new_event_id]));
    }
    else {
      $form['form_wrapper_bottom']['#markup'] = t('New Event state is <strong>@state</strong>.', array('@state' => $state_options[$new_event_id]));
    }
  }

  return $form;
}


/**
 * Implement hook_theme().
 */
function rooms_availability_theme() {
  return array(
    'rooms_three_month_calendar' => array(
      'template' => 'rooms_three_month_calendar',
      'variables' => array(
        'url' => NULL,
        'form' => NULL,
        'year' => NULL,
        'month' => NULL,
      ),
    ),
  );
}


/**
 * Sets event ids
 *
 * @todo - Make this depend on a paramenter
 */
function rooms_availability_assign_id($id, $status = '1') {
  // Add eleven for now - this allows for 10 states that do not
  // refer to a specific booking
  $id = $id + 11;

  if ($status == '0') {
    return -($id);
  }
  else {
    return $id;
  }
}


/**
 * Given an event state it returns the valid booking id
 */
function rooms_availability_return_id($id) {
  // Make sure we are not looking for negative ids;
  $id = abs($id);

  $id = $id - 11;

  return $id;
}

/**
 * Implements hook_form__FORM_ID_alter().
 * FORM_ID = rooms_booking_settings
 */
function rooms_availability_form_rooms_booking_settings_alter(&$form, &$form_state, $form_id) {
  $form['label_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Calendar Color Codes & Labels'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['label_settings']['rooms_not_available_color'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" color', array('@availability_status' => t('Unavailable'))),
    '#size' => 10,
    '#maxlength' => 7,
    '#default_value' => variable_get('rooms_not_available_color', '#FF0000'),
    '#element_validate' => array('rooms_availability_validate_hex_color'),
    '#dependency' => array('edit-row-options-colors-legend' => array('type')),
    '#prefix' => '<div class="rooms-colorpicker-wrapper form-wrapper">',
    '#suffix' => '<div class="rooms-colorpicker"></div></div>',
    '#attributes' => array('class' => array('rooms-edit-colorpicker')),
    '#attached' => array(
      // Add Farbtastic color picker.
      'library' => array(
        array('system', 'farbtastic'),
      ),
      // Add javascript to trigger the colorpicker.
      'js' => array(drupal_get_path('module', 'rooms_availability') . '/js/rooms_color.js'),
    ),
  );

  $form['label_settings']['rooms_not_available_text'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" label', array('@availability_status' => t('Unavailable'))),
    '#size' => 10,
    '#maxlength' => 50,
    '#default_value' => variable_get('rooms_not_available_text', 'N/A'),
  );

  $form['label_settings']['rooms_available_color'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" color', array('@availability_status' => t('Available'))),
    '#size' => 10,
    '#maxlength' => 7,
    '#default_value' => variable_get('rooms_available_color', '#8CBF62'),
    '#element_validate' => array('rooms_availability_validate_hex_color'),
    '#dependency' => array('edit-row-options-colors-legend' => array('type')),
    '#prefix' => '<div class="rooms-colorpicker-wrapper">',
    '#suffix' => '<div class="rooms-colorpicker"></div></div>',
    '#attributes' => array('class' => array('rooms-edit-colorpicker')),
    '#attached' => array(
      // Add Farbtastic color picker.
      'library' => array(
        array('system', 'farbtastic'),
      ),
      // Add javascript to trigger the colorpicker.
      'js' => array(drupal_get_path('module', 'rooms_availability') . '/js/rooms_color.js'),
    ),
  );

  $form['label_settings']['rooms_available_text'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" label', array('@availability_status' => t('Available'))),
    '#size' => 10,
    '#maxlength' => 50,
    '#default_value' => variable_get('rooms_available_text', 'AV'),
  );

  $form['label_settings']['rooms_on_request_color'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" color', array('@availability_status' => t('Available on Request'))),
    '#size' => 10,
    '#maxlength' => 7,
    '#default_value' => variable_get('rooms_on_request_color', '#C5C5C5'),
    '#element_validate' => array('rooms_availability_validate_hex_color'),
    '#dependency' => array('edit-row-options-colors-legend' => array('type')),
    '#prefix' => '<div class="rooms-colorpicker-wrapper">',
    '#suffix' => '<div class="rooms-colorpicker"></div></div>',
    '#attributes' => array('class' => array('rooms-edit-colorpicker')),
    '#attached' => array(
      // Add Farbtastic color picker.
      'library' => array(
        array('system', 'farbtastic'),
      ),
      // Add javascript to trigger the colorpicker.
      'js' => array(drupal_get_path('module', 'rooms_availability') . '/js/rooms_color.js'),
    ),
  );

  $form['label_settings']['rooms_on_request_text'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" label', array('@availability_status' => t('Available on Request'))),
    '#size' => 10,
    '#maxlength' => 50,
    '#default_value' => variable_get('rooms_on_request_text', 'ON-REQ'),
  );

  $form['label_settings']['rooms_anon_booking_color'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" color', array('@availability_status' => t('Anonymous booking'))),
    '#size' => 10,
    '#maxlength' => 7,
    '#default_value' => variable_get('rooms_anon_booking_color', '#481600'),
    '#element_validate' => array('rooms_availability_validate_hex_color'),
    '#dependency' => array('edit-row-options-colors-legend' => array('type')),
    '#prefix' => '<div class="rooms-colorpicker-wrapper">',
    '#suffix' => '<div class="rooms-colorpicker"></div></div>',
    '#attributes' => array('class' => array('rooms-edit-colorpicker')),
    '#attached' => array(
      // Add Farbtastic color picker.
      'library' => array(
        array('system', 'farbtastic'),
      ),
      // Add javascript to trigger the colorpicker.
      'js' => array(drupal_get_path('module', 'rooms_availability') . '/js/rooms_color.js'),
    ),
  );

  $form['label_settings']['rooms_anon_booking_text'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" label', array('@availability_status' => t('Anonymous booking'))),
    '#size' => 10,
    '#maxlength' => 50,
    '#default_value' => variable_get('rooms_anon_booking_text', 'A-B'),
  );

  $form['label_settings']['rooms_unconfirmed_booking_color'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" color', array('@availability_status' => t('Unconfirmed booking'))),
    '#size' => 10,
    '#maxlength' => 7,
    '#default_value' => variable_get('rooms_unconfirmed_booking_color', '#481600'),
    '#element_validate' => array('rooms_availability_validate_hex_color'),
    '#dependency' => array('edit-row-options-colors-legend' => array('type')),
    '#prefix' => '<div class="rooms-colorpicker-wrapper">',
    '#suffix' => '<div class="rooms-colorpicker"></div></div>',
    '#attributes' => array('class' => array('rooms-edit-colorpicker')),
    '#attached' => array(
      // Add Farbtastic color picker.
      'library' => array(
        array('system', 'farbtastic'),
      ),
      // Add javascript to trigger the colorpicker.
      'js' => array(drupal_get_path('module', 'rooms_availability') . '/js/rooms_color.js'),
    ),
  );

  $form['label_settings']['rooms_unconfirmed_booking_text'] = array(
    '#type' => 'textfield',
    '#title' => t('"@availability_status" label', array('@availability_status' => t('Unconfirmed booking'))),
    '#size' => 10,
    '#maxlength' => 50,
    '#default_value' => variable_get('rooms_unconfirmed_booking_text', 'UNCONF'),
  );

  $form['label_settings']['rooms_view_unit_name'] = array(
    '#type' => 'checkboxes',
    '#options' => array(
      '1' => t('Display unit name in place of availability state label.'),
    ),
    '#default_value' => variable_get('rooms_view_unit_name', array('')),
  );
}


/**
 * Utility function to validate hex color numbers
 */
function rooms_availability_validate_hex_color($element, &$form_state) {
  if (!preg_match('/^#[a-f0-9]{6}$/i', $element['#value'])) {
    form_error($element, t('This is not a valid hexadecimal color!'));
  }
}


/**
 * Creates a pair of date popup fields for Bulk Unit Management operations.
 *
 * This function is similar to rooms_date_range_fields() in the main rooms
 * module, however, since the bulk management UI limits date range input to
 * act on the current month only, we've modified the original functionality
 * to also make the same limits for the datepicker as well to only allow days
 * within the specified month and year.
 */
function rooms_availability_date_range_fields($year, $month) {
  $date_range_fields = array();

  $date_format = str_replace('-', '/', variable_get('rooms_date_format', 'd-m-Y'));

  // Calculate min and max dates of the specified year/month.
  $date = new DateTime();
  $date->setDate($year, $month, 01);
  $min_date = $date->format($date_format);
  $date->modify('last day of this month');
  $max_date = $date->format($date_format);

  // Create unique ids and selectors for each picker.
  $start_date_id = drupal_html_id('datepicker-start-date');
  $start_date_selector = '#' . $start_date_id . ' .form-text';

  $end_date_id = drupal_html_id('datepicker-end-date');
  $end_date_selector = '#' . $start_date_id . ' .form-text';

  // Specify the default datepicker parameters (see date_popup_element_info())
  $datepicker_options = array(
    'dateFormat' => rooms_dateFormatTojQueryUIDatePickerFormat($date_format),
    'minDate' => $min_date,
    'maxDate' => $max_date,
    'defaultDate' => $min_date,
    'numberOfMonths' => 1,
  );

  $date_range_fields['rooms_start_date'] = array(
    '#prefix' => '<div class="form-wrapper rooms-date-range"><div class="start-date" id="' . $start_date_id . '">',
    '#suffix' => '</div>',
    '#type' => 'date_popup',
    '#title' => t('Start Date'),
    '#date_type' => DATE_DATETIME,
    '#date_format' => $date_format,
    '#date_increment' => 1,
    '#date_year_range' => '-1:+3',
    // Default datepicker parameters defined above, with an additional parameter
    // linking to the jQuery selector for the end datepicker.
    '#datepicker_options' => array_merge($datepicker_options, array('endDateSelector' => $end_date_selector)),
    '#required' => TRUE,
  );


  $date_range_fields['rooms_end_date'] = array(
    '#prefix' => '<div class="end-date" id="' . $end_date_id . '">',
    '#suffix' => '</div></div>',
    '#type' => 'date_popup',
    '#title' => t('End Date'),
    '#date_type' => DATE_DATETIME,
    '#date_format' => $date_format,
    '#date_increment' => 1,
    '#date_year_range' => '-1:+3',
    // Default parameters defined above, with an additional parameter
    // parameter linking to the jQuery selector for the start datepicker.
    '#datepicker_options' => array_merge($datepicker_options, array('startDateSelector' => $start_date_selector)),
    '#required' => TRUE,
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'rooms') . '/css/rooms_date_range_fields.css',
      ),
      'js' => array(
        drupal_get_path('module', 'rooms') . '/js/rooms_date_popup.js',
        array(
         'data' => array(
            'rooms' => array(
              'roomsStartYear' => $year,
              'roomsStartMonth' => $month,
              'roomsBookingStartDay' => variable_get('rooms_booking_start_date', 1),
              'roomsDateFormat' => rooms_dateFormatTojQueryUIDatePickerFormat($date_format),
              // Here we create a listing of all datepickers registered on the
              // current page. This is available for use in your own custom
              // jQuery scripts as Drupal.settings.rooms.datepickers.
              'datepickers' => array(
                $start_date_selector => array(
                  'endDateSelector' => $end_date_selector,
                ),
              ),
            ),
          ),
          'type' => 'setting',
        ),
      ),
    ),
  );
  return $date_range_fields;
}


/**
 * Helper validate function to ensure that at least one room is selected.
 */
function _rooms_availability_select_rooms_validation($form_state) {
  $select_rooms = FALSE;
  if (variable_get('ROOMS_SELECT_ALL_PAGES_PR') == 'false') {
    foreach ($form_state['values'] as $key => $value) {
      if (strpos($key, 'rooms-') === 0 && $value == '1') {
        $select_rooms = TRUE;
      }
    }
  }
  else {
    $select_rooms = TRUE;
  }

  if (!$select_rooms) {
    form_set_error('select-all', t('Select at least one unit.'));
  }
}
